INSERT INTO provinces (`name`, `region_id`)
VALUES
    ('Arica', (SELECT id FROM auth.regions WHERE ordinal LIKE 'XV')),
    ('Parinacota', (SELECT id FROM auth.regions WHERE ordinal LIKE 'XV')),
    ('Iquique', (SELECT id FROM auth.regions WHERE ordinal LIKE 'I')),
    ('Tamarugal', (SELECT id FROM auth.regions WHERE ordinal LIKE 'I')),
    ('Antofagasta', (SELECT id FROM auth.regions WHERE ordinal LIKE 'II')),
    ('El Loa', (SELECT id FROM auth.regions WHERE ordinal LIKE 'II')),
    ('Tocopilla', (SELECT id FROM auth.regions WHERE ordinal LIKE 'II')),
    ('Copiapó', (SELECT id FROM auth.regions WHERE ordinal LIKE 'III')),
    ('Chañaral', (SELECT id FROM auth.regions WHERE ordinal LIKE 'III')),
    ('Huasco', (SELECT id FROM auth.regions WHERE ordinal LIKE 'III')),
    ('Elqui', (SELECT id FROM auth.regions WHERE ordinal LIKE 'IV')),
    ('Choapa', (SELECT id FROM auth.regions WHERE ordinal LIKE 'IV')),
    ('Limarí', (SELECT id FROM auth.regions WHERE ordinal LIKE 'IV')),
    ('Valparaíso', (SELECT id FROM auth.regions WHERE ordinal LIKE 'V')),
    ('Isla de Pascua', (SELECT id FROM auth.regions WHERE ordinal LIKE 'V')),
    ('Los Andes', (SELECT id FROM auth.regions WHERE ordinal LIKE 'V')),
    ('Petorca', (SELECT id FROM auth.regions WHERE ordinal LIKE 'V')),
    ('Quillota', (SELECT id FROM auth.regions WHERE ordinal LIKE 'V')),
    ('San Antonio', (SELECT id FROM auth.regions WHERE ordinal LIKE 'V')),
    ('San Felipe de Aconcagua', (SELECT id FROM auth.regions WHERE ordinal LIKE 'V')),
    ('Marga Marga', (SELECT id FROM auth.regions WHERE ordinal LIKE 'V')),
    ('Cachapoal', (SELECT id FROM auth.regions WHERE ordinal LIKE 'VI')),
    ('Cardenal Caro', (SELECT id FROM auth.regions WHERE ordinal LIKE 'VI')),
    ('Colchagua', (SELECT id FROM auth.regions WHERE ordinal LIKE 'VI')),
    ('Talca', (SELECT id FROM auth.regions WHERE ordinal LIKE 'VII')),
    ('Cauquenes', (SELECT id FROM auth.regions WHERE ordinal LIKE 'VII')),
    ('Curicó', (SELECT id FROM auth.regions WHERE ordinal LIKE 'VII')),
    ('Linares', (SELECT id FROM auth.regions WHERE ordinal LIKE 'VII')),
    ('Diguillín', (SELECT id FROM auth.regions WHERE ordinal LIKE 'XVI')),
    ('Itata', (SELECT id FROM auth.regions WHERE ordinal LIKE 'XVI')),
    ('Punilla', (SELECT id FROM auth.regions WHERE ordinal LIKE 'XVI')),
    ('Concepción', (SELECT id FROM auth.regions WHERE ordinal LIKE 'VIII')),
    ('Arauco', (SELECT id FROM auth.regions WHERE ordinal LIKE 'VIII')),
    ('BioBío', (SELECT id FROM auth.regions WHERE ordinal LIKE 'VIII')),
    ('Cautín', (SELECT id FROM auth.regions WHERE ordinal LIKE 'IX')),
    ('Malleco', (SELECT id FROM auth.regions WHERE ordinal LIKE 'IX')),
    ('Valdivia', (SELECT id FROM auth.regions WHERE ordinal LIKE 'XIV')),
    ('Ranco', (SELECT id FROM auth.regions WHERE ordinal LIKE 'XIV')),
    ('Llanquihue', (SELECT id FROM auth.regions WHERE ordinal LIKE 'X')),
    ('Chiloé', (SELECT id FROM auth.regions WHERE ordinal LIKE 'X')),
    ('Osorno', (SELECT id FROM auth.regions WHERE ordinal LIKE 'X')),
    ('Palena', (SELECT id FROM auth.regions WHERE ordinal LIKE 'X')),
    ('Coyhaique', (SELECT id FROM auth.regions WHERE ordinal LIKE 'XI')),
    ('Aisén', (SELECT id FROM auth.regions WHERE ordinal LIKE 'XI')),
    ('Capitán Pratt', (SELECT id FROM auth.regions WHERE ordinal LIKE 'XI')),
    ('General Carrera', (SELECT id FROM auth.regions WHERE ordinal LIKE 'XI')),
    ('Magallanes', (SELECT id FROM auth.regions WHERE ordinal LIKE 'XII')),
    ('Antártica Chilena', (SELECT id FROM auth.regions WHERE ordinal LIKE 'XII')),
    ('Tierra del Fuego', (SELECT id FROM auth.regions WHERE ordinal LIKE 'XII')),
    ('Última Esperanza', (SELECT id FROM auth.regions WHERE ordinal LIKE 'XII')),
    ('Santiago', (SELECT id FROM auth.regions WHERE ordinal LIKE 'RM')),
    ('Cordillera', (SELECT id FROM auth.regions WHERE ordinal LIKE 'RM')),
    ('Chacabuco', (SELECT id FROM auth.regions WHERE ordinal LIKE 'RM')),
    ('Maipo', (SELECT id FROM auth.regions WHERE ordinal LIKE 'RM')),
    ('Melipilla', (SELECT id FROM auth.regions WHERE ordinal LIKE 'RM')),
    ('Talagante', (SELECT id FROM auth.regions WHERE ordinal LIKE 'RM'));