name: Delete Branch After Merge

on:
  pull_request:
    types:
      - closed
    branches:
      - develop
      - qa
      - pre-prod

jobs:
  delete-branch:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Delete branch
        run: |
          BRANCH_NAME=${{ github.head_ref }}
          echo "Deleting branch $BRANCH_NAME..."
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git push origin --delete $BRANCH_NAME
