name: Delete Merged Compare Branch

on:
  pull_request:
    types:
      - closed

jobs:
  delete_merged_branch:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'develop'
    runs-on: ubuntu-latest
    steps:
      - name: Delete merged branch
        run: |
          BRANCH_NAME=${{ github.event.pull_request.head.ref }}

          echo "La rama mergeada es: $BRANCH_NAME"

          # Elimina la rama remota
          git push origin --delete $BRANCH_NAME

